apiVersion: apps/v1
kind: Deployment #object type
metadata:
    name: worker-deployment #name of object we going to create. so, deployment will have name of client-deployment
spec:
    replicas: 1 #number of different pods that it will create. Create 1 pod using template shown below. 
    selector: #
        matchLabels:
            component: worker #component inside application we waorking on is server

    template: #listing out configuration of every single pod created by deployment object. Every pod created will have label as web and image as multi-client
        metadata:
            labels:
                component: worker #label must match up with the selector tag
        spec:
            containers:
                - name: worker
                  image: stephengrider/multi-worker #image of docker id. we have to add enviornment variable here
                  #there is nothing to connect to multi-worker to make a request so, therefore don't have port and service assign it.
                  #We make sense of serices when we want to have request going into the single pod so, no need for service or pod.
                  env:
                    - name: REDIS_HOST #name of envrionmental variable
                      value: redis-cluster-ip-service #value of envrionmental variable. reference how its going to reach out to redis. 
                      #We give name of the clusterIP to get into redis pod
                    - name: REDIS_PORT
                      value: "6379"
        
